sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
env:
  - LUAJIT=OFF  
cache: apt
addons:
  apt:
    packages:
      - libboost-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-iostreams-dev
      - libboost-thread-dev
      - libboost-date-time-dev
      - libcrypto++-dev
      - liblua5.2-dev
      - libluajit-5.1-dev
      - libmysqlclient-dev
      - libpugixml-dev 
      - libsqlite3-dev
      - unixodbc-dev
      - libpq-dev
before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
script: make -j2
