image: Visual Studio 2017

shallow_clone: true

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

only_commits:
  files:
    - src/
    - vc14/
    - appveyor.yml

install:
  - cmd : vcpkg install boost-iostreams:x64-windows
  - cmd : vcpkg install boost-asio:x64-windows
  - cmd : vcpkg install boost-system:x64-windows
  - cmd : vcpkg install boost-filesystem:x64-windows
  - cmd : vcpkg install boost-variant:x64-windows
  - cmd : vcpkg install boost-lockfree:x64-windows
  - cmd : vcpkg install boost-date-time:x64-windows
  - cmd : vcpkg install boost-thread:x64-windows
  - cmd : vcpkg install openssl:x64-windows
  - cmd : vcpkg install luajit:x64-windows
  - cmd : vcpkg install libmariadb:x64-windows
  - cmd : vcpkg install libxml2:x64-windows
  - cmd : vcpkg install sqlite3:x64-windows
  - cmd : vcpkg install libpq:x64-windows

build:
  parallel: true
  # MSBuild verbosity level
  #verbosity: detailed

cache:
  - c:\tools\vcpkg\installed\

artifacts:
  - path: vc14\**\theforgottenserver*.exe
  - path: vc14\**\*.dll