trigger:
- master

pool:
  vmImage: 'macOS-10.13'

steps:
- script: brew install boost luajit mysql-connector-c pugixml sqlite libpq cryptopp
- script: cd 3888 |
- script: mkdir build
- script: cd build
- script: cmake .. 
- script: make